const events = [
  {
    title: 'Malappuram Floodlight Football Match',
    date: 'Wednesday, July 14',
    location: 'Calicut',
    price: '$20.00',
    category: 'Sports',
    image: 'https://via.placeholder.com/400x200?text=Football+Match',
  },
  {
    title: 'National Tech Seminar 2022',
    date: 'Monday, December 24, 2023',
    location: 'Kondothy, Malappuram',
    price: '$20.00 - $100.00',
    category: 'Tech',
    image: 'https://via.placeholder.com/400x200?text=Tech+Seminar',
  },
  {
    title: 'AI Innovation Summit 2023',
    date: 'Saturday, November 18, 2023',
    location: 'Bangalore',
    price: '$50.00',
    category: 'AI',
    image: 'https://via.placeholder.com/400x200?text=AI+Summit',
  },
  {
    title: 'Blockchain Developers Conference',
    date: 'Friday, October 27, 2023',
    location: 'Hyderabad',
    price: '$75.00',
    category: 'Blockchain',
    image: 'https://via.placeholder.com/400x200?text=Blockchain+Conference',
  },
  {
    title: 'Kerala Premier League Cricket',
    date: 'Sunday, August 20, 2023',
    location: 'Trivandrum',
    price: '$15.00',
    category: 'Sports',
    image: 'https://via.placeholder.com/400x200?text=Cricket+Match',
  },
  {
    title: 'Tech Startup Expo 2023',
    date: 'Tuesday, September 12, 2023',
    location: 'Mumbai',
    price: '$30.00',
    category: 'Tech',
    image: 'https://via.placeholder.com/400x200?text=Startup+Expo',
  },
  {
    title: 'AI in Healthcare Workshop',
    date: 'Thursday, October 5, 2023',
    location: 'Chennai',
    price: '$40.00',
    category: 'AI',
    image: 'https://via.placeholder.com/400x200?text=AI+Healthcare',
  },
  {
    title: 'Crypto & Blockchain Hackathon',
    date: 'Saturday, November 11, 2023',
    location: 'Pune',
    price: '$60.00',
    category: 'Blockchain',
    image: 'https://via.placeholder.com/400x200?text=Blockchain+Hackathon',
  },
  {
    title: 'International Marathon 2023',
    date: 'Sunday, December 3, 2023',
    location: 'Delhi',
    price: '$25.00',
    category: 'Sports',
    image: 'https://via.placeholder.com/400x200?text=Marathon',
  },
  {
    title: 'Future of Tech Conference',
    date: 'Wednesday, January 10, 2024',
    location: 'Bangalore',
    price: '$100.00',
    category: 'Tech',
    image: 'https://via.placeholder.com/400x200?text=Tech+Conference',
  },
  {
    title: 'AI for Business Leaders',
    date: 'Friday, February 16, 2024',
    location: 'Mumbai',
    price: '$80.00',
    category: 'AI',
    image: 'https://via.placeholder.com/400x200?text=AI+Business',
  },
  {
    title: 'Blockchain for Beginners Workshop',
    date: 'Saturday, March 23, 2024',
    location: 'Hyderabad',
    price: '$45.00',
    category: 'Blockchain',
    image: 'https://via.placeholder.com/400x200?text=Blockchain+Workshop',
  },
  {
    title: 'Kerala Badminton Championship',
    date: 'Sunday, April 14, 2024',
    location: 'Kochi',
    price: '$10.00',
    category: 'Sports',
    image: 'https://via.placeholder.com/400x200?text=Badminton+Championship',
  },
  {
    title: 'Tech Fest 2024',
    date: 'Monday, May 20, 2024',
    location: 'Chennai',
    price: '$35.00',
    category: 'Tech',
    image: 'https://via.placeholder.com/400x200?text=Tech+Fest',
  },
  {
    title: 'AI & Machine Learning Expo',
    date: 'Wednesday, June 12, 2024',
    location: 'Pune',
    price: '$55.00',
    category: 'AI',
    image: 'https://via.placeholder.com/400x200?text=AI+Expo',
  },
  {
    title: 'Blockchain Security Summit',
    date: 'Friday, July 19, 2024',
    location: 'Bangalore',
    price: '$90.00',
    category: 'Blockchain',
    image: 'https://via.placeholder.com/400x200?text=Blockchain+Security',
  },
  {
    title: 'Kerala Tennis Open 2024',
    date: 'Sunday, August 25, 2024',
    location: 'Trivandrum',
    price: '$20.00',
    category: 'Sports',
    image: 'https://via.placeholder.com/400x200?text=Tennis+Open',
  },
  {
    title: 'Tech Innovators Meetup',
    date: 'Tuesday, September 17, 2024',
    location: 'Mumbai',
    price: '$40.00',
    category: 'Tech',
    image: 'https://via.placeholder.com/400x200?text=Tech+Meetup',
  },
  {
    title: 'AI Ethics and Governance Conference',
    date: 'Thursday, October 24, 2024',
    location: 'Delhi',
    price: '$70.00',
    category: 'AI',
    image: 'https://via.placeholder.com/400x200?text=AI+Ethics',
  },
  {
    title: 'Blockchain in Finance Symposium',
    date: 'Saturday, November 30, 2024',
    location: 'Hyderabad',
    price: '$85.00',
    category: 'Blockchain',
    image: 'https://via.placeholder.com/400x200?text=Blockchain+Finance',
  },
];

export default events;